import {
  AlertCircle,
  BookOpen,
  Compass,
  Crosshair,
  Eye,
  FileText,
  Ghost,
  Heart,
  Landmark,
  Music,
  Rocket,
  Shield,
  ShieldAlert,
  Smile,
  Sparkles,
  Theater,
  Trophy,
  Users,
  WandSparkles,
  Zap,
} from 'lucide-react';

import { Genre } from '@/types/base-movie-cards';

export const genresData: Genre[] = [
  { name: 'Action', slug: 'action', icon: Zap },
  { name: 'Comedy', slug: 'comedy', icon: Smile },
  { name: 'Drama', slug: 'drama', icon: Theater },
  { name: 'Thriller', slug: 'thriller', icon: AlertCircle },
  { name: 'Horror', slug: 'horror', icon: Ghost },
  { name: 'Sci-Fi', slug: 'sci-fi', icon: Rocket },
  { name: 'Fantasy', slug: 'fantasy', icon: WandSparkles },
  { name: 'Adventure', slug: 'adventure', icon: Compass },
  { name: 'Romance', slug: 'romance', icon: Heart },
  { name: 'Animation', slug: 'animation', icon: Sparkles },
  { name: 'Crime', slug: 'crime', icon: ShieldAlert },
  { name: 'Mystery', slug: 'mystery', icon: Eye },
  { name: 'Biography', slug: 'biography', icon: BookOpen },
  { name: 'History', slug: 'history', icon: Landmark },
  { name: 'Family', slug: 'family', icon: Users },
  { name: 'War', slug: 'war', icon: Crosshair },
  { name: 'Musical', slug: 'musical', icon: Music },
  { name: 'Sport', slug: 'sport', icon: Trophy },
  { name: 'Documentary', slug: 'documentary', icon: FileText },
  { name: 'Superhero', slug: 'superhero', icon: Shield },
];
