export const moviesBigBannerData = [
  'Fight Club',
  'The Wolf of Wall Street',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  'The Lion King',
  'Harry Potter and the Philosophers Stone',
];

export const topRatedMoviesListData = [
  'The Shawshank Redemption',
  'The Dark Knight',
  'Inception',
  'Titanic',
  'Avatar',
  'Gladiator',
  'The Matrix',
  'Forrest Gump',
  'The Lord of the Rings: The Fellowship of the Ring',
  'Interstellar',
  'Joker',
  'The Avengers',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  'The Lion King',
  'Harry Potter and the Philosophers Stone',
  'The Godfather',
  'Fight Club',
  'The Wolf of Wall Street',
  'Spider-Man: No Way Home',
  'Top Gun: Maverick',
];

export const sciFiFantasyMoviesListData = [
  'Dune',
  'Blade Runner 2049',
  'Arrival',
  'Mad Max: Fury Road',
  'Edge of Tomorrow',
  'The Martian',
  'Doctor Strange',
  'Guardians of the Galaxy',
  'Star Wars: Episode III – Revenge of the Sith',
  'The Hunger Games',
  'Ready Player One',
  'Eternals',
  'Oblivion',
  'Tenet',
  'The Fifth Element',
  'Minority Report',
  'A Quiet Place',
  'The Maze Runner',
  'Alita: Battle Angel',
  'I Am Legend',
];
